-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 10:25:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema facturando
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facturando
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facturando` DEFAULT CHARACTER SET utf8 ;
USE `facturando` ;

-- -----------------------------------------------------
-- Table `facturando`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `condicion` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturando`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`articulo` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT NOT NULL,
  `codigo` VARCHAR(50) NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(512) NULL,
  `imagen` VARCHAR(50) NULL,
  `condicion` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_articulo`),
  INDEX `fk_hacia_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_hacia_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `facturando`.`categoria` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturando`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(20) NULL,
  `correo` VARCHAR(50) NULL,
  `cargo` VARCHAR(20) NULL,
  `login` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(64) NOT NULL,
  `condicion` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturando`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `tipo_persona` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NULL,
  `num_documento` VARCHAR(20) NULL,
  `ciudad` VARCHAR(45) NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(20) NULL,
  `correo` VARCHAR(50) NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturando`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`ingreso` (
  `id_ingreso` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(45) NULL,
  `numero_comprobante` VARCHAR(45) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `iva` DECIMAL(19,3) NULL,
  `retefuente` DECIMAL(19,3) NULL,
  `reteica` DECIMAL(19,3) NULL,
  `reteiva` DECIMAL(19,3) NULL,
  `total_compra` DECIMAL(19,3) NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_ingreso`),
  INDEX `fk_hacia_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_hacia_persona_idx` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_hacia_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `facturando`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_hacia_persona`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `facturando`.`persona` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturando`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`detalle_ingreso` (
  `id_detalle_ingreso` INT NOT NULL AUTO_INCREMENT,
  `id_ingreso` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_compra` DECIMAL(19,3) NOT NULL,
  `precio_venta` DECIMAL(19,3) NOT NULL,
  PRIMARY KEY (`id_detalle_ingreso`),
  INDEX `fk_hacia_ingreso_idx` (`id_ingreso` ASC) VISIBLE,
  INDEX `fk_hacia_articulo_idx` (`id_articulo` ASC) VISIBLE,
  CONSTRAINT `fk_hacia_ingreso`
    FOREIGN KEY (`id_ingreso`)
    REFERENCES `facturando`.`ingreso` (`id_ingreso`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_hacia_articulo`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `facturando`.`articulo` (`id_articulo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturando`.`mi_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`mi_empresa` (
  `id_mi_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `numero_documento` VARCHAR(20) NOT NULL,
  `cuidad` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `logo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_mi_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturando`.`credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`credito` (
  `id_credito` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `cuota` VARCHAR(45) NOT NULL,
  `cupo_disponible` DECIMAL(19,3) NOT NULL,
  PRIMARY KEY (`id_credito`),
  INDEX `fk_hacia_persona_idx` (`id_persona` ASC) VISIBLE,
  INDEX `fk_hacia_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_hacia_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `facturando`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hacia_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `facturando`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturando`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`venta` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_mi_empresa` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `id_detalle_ingreso` INT NOT NULL,
  `id_credito` INT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `iva` DECIMAL(19,3) NULL,
  `rete_fuente` DECIMAL(19,3) NULL,
  `rete_iva` DECIMAL(19,3) NULL,
  `valor_unitario` DECIMAL(19,3) NOT NULL,
  `subtotal` DECIMAL(19,3) NOT NULL,
  `total` DECIMAL(19,3) NOT NULL,
  `descuento` DECIMAL(19,3) NULL,
  `estado` VARCHAR(20) NOT NULL,
  `observacion` VARCHAR(256) NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_hacia_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_mi_empresa_idx` (`id_mi_empresa` ASC) VISIBLE,
  INDEX `fk_hacia_articulo_idx` (`id_articulo` ASC) VISIBLE,
  INDEX `fk_hacia_detalle_ingreso_idx` (`id_detalle_ingreso` ASC) VISIBLE,
  INDEX `fk_hacia_credito_idx` (`id_credito` ASC) VISIBLE,
  CONSTRAINT `fk_hacia_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `facturando`.`persona` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `facturando`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_mi_empresa`
    FOREIGN KEY (`id_mi_empresa`)
    REFERENCES `facturando`.`mi_empresa` (`id_mi_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_hacia_articulo`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `facturando`.`articulo` (`id_articulo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_hacia_detalle_ingreso`
    FOREIGN KEY (`id_detalle_ingreso`)
    REFERENCES `facturando`.`detalle_ingreso` (`id_detalle_ingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hacia_credito`
    FOREIGN KEY (`id_credito`)
    REFERENCES `facturando`.`credito` (`id_credito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturando`.`usuario_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturando`.`usuario_permiso` (
  `id_usuario_permiso` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario_permiso`),
  INDEX `fk_hacia_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_hacia_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `facturando`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
