/*CREAR*/
CREATE DATABASE aprendiendo;


/*EMPLEADO*/
USE APRENDIENDO;
CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	CEDULA VARCHAR(50) NOT NULL,
	ESTADO_CIVIL VARCHAR(1) NOT NULL,
	GENERO VARCHAR(1) NOT NULL,
	EDAD INT NOT NULL
);

/*insertar*/
INSERT INTO empleado (nombre, apellido, cedula, estado_civil, genero, edad)
VALUES ('julio', 'lopez', '34435','1','1',23);

/*seleccionar*/
SELECT * FROM EMPLEADO ORDER BY ID_EMPLEADO ASC;

/*eliminar tabla*/
DROP TABLE EMPLEADO;



/*NUMERO*/
USE APRENDIENDO;
CREATE TABLE NUMERO(
	ID_NUMERO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VALOR INT NOT NULL
);

/*insertar*/
INSERT INTO NUMERO (VALOR)
VALUES ('el numero 2 es par');

/*seleccionar*/
SELECT * FROM NUMERO;


/*borrar registro*/
DELETE FROM NUMERO WHERE ID_NUMERO = 1;

/*agregar columna*/
ALTER TABLE NUMERO
ADD DESCRIPCION VARCHAR(50);

/*modificar tipo de dato columna*/
ALTER TABLE NUMERO
MODIFY COLUMN VALOR INT;