/*CREAR*/
CREATE DATABASE aprendiendo;

USE APRENDIENDO;
CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	CEDULA VARCHAR(50) NOT NULL,
	ESTADO_CIVIL VARCHAR(1) NOT NULL,
	GENERO VARCHAR(1) NOT NULL,
	EDAD INT NOT NULL
);

USE APRENDIENDO;
CREATE TABLE NUMERO(
	ID_NUMERO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VALOR INT NOT NULL
);
SELECT * FROM NUMERO;


/*INSERTAR*/
INSERT INTO empleado (nombre, apellido, cedula, estado_civil, genero, edad)
VALUES ('julio', 'lopez', '34435','1','1',23);

SELECT * FROM EMPLEADO;

INSERT INTO NUMERO (VALOR)
VALUES ('el numero 2 es par');

/*ACTUALIZAR*/

/*ELIMINAR*/
DROP TABLE EMPLEADO;

DELETE FROM NUMERO WHERE ID_NUMERO = 1;

/*ALTERAR*/
ALTER TABLE NUMERO
ADD DESCRIPCION VARCHAR(50);

ALTER TABLE NUMERO
MODIFY COLUMN VALOR INT;